### ISSUE TITLE
\d not working

### ISSUE THREAD

**Issue by DanielRuf** [projectdiscovery/dsl#15]
When using the following code, nuclei 2.8.6 throws an error:

`"regex('(?i)server: apache/\d', all_headers)"`

`Error occurred loading template servertokens.yaml: yaml: line 23: found unknown escape character`

Why does this not work as expected? Does this need multiple backslashes? According to https://pkg.go.dev/regexp it should support `\d`.

Only `"regex('(?i)server: apache/[0-9]', all_headers)"` works.

**Comment by brenocss** [comment]
Try `\\d`

**Comment by DanielRuf** [comment]
My test results:

* `...\d`' = error
* `...\\d'` = not triggered
* `...[\\d]'` = not triggered
* `...[0-9]'` = triggered

Would it make sense to move this issue to the main repo since nuclei 2.8.6 was released before the dsl project was split from there?

**Comment by tarunKoyalwar** [comment]
@DanielRuf , I think keeping it here makes more sense . also can you try switching the quotes i.e

```console
'regex("(?i)server: apache/\d", all_headers)'
```

more details on how to escape and lots of other stuff can be found here https://github.com/Knetic/govaluate

**Comment by DanielRuf** [comment]
@tarunKoyalwar thanks, the proposed solution seems to works. Looks like I have to study a bit better how the escaping works in this project.

Not sure what I did wrong when I tried to switch the quote styles (single to double, double to single).
