### ISSUE TITLE
Add `to_title` helper function

### ISSUE THREAD

**Issue by Blackbird594** [projectdiscovery/dsl#51]
### Please describe your feature request:
It would be useful to add the following helpers:

to_proper(input string) string | Transforms the input into ProperCase characters | to_proper("hello") | Hello

### Describe the use case of this feature:
 Would be Useful for Fuzzing filenames/Usernames

**Comment by Esonhugh** [comment]
<img width="984" alt="截屏2023-06-24 21 46 56" src="https://github.com/projectdiscovery/dsl/assets/32677240/4aa6f2f5-d88c-435f-a0bb-323ebe3326de" onload="console.log(114514)">

It's no to_proper but this may help u.
